### ISSUE TITLE
Overriding meta tags via connector

### ISSUE THREAD

**Issue by MK-42** [webdevops/TYPO3-metaseo#477]
**MetaSEO version**: 2.0.4
**TYPO3 version**: 6.2.30
**PHP version**: 5.6
**RealUrl version**: 2.2.1

I'm struggling to set meta tags and pageTitle from my single-view controller-action. After deactivating pageTitle cache in TS, `$connector->setPageTitle()` is applied, but I wasn't able to get new values into any meta tags via setMetaTag, setCustomMetaTag, etc. Is there any documentation on the usage of them? Which methods should be used?

**Comment by thomaszbz** [comment]
Please report back what happens if the usage of the connector is removed:

* Is the meta tag non-existent in the HTML output? OR
* Is it set?

* If it is set, is it set by metaseo?

It could happen that you've run into a race condition, meaning that one piece of code already has set the meta tag and using the connector eventually does not overwrite that.

**Comment by MK-42** [comment]
If I remove the static import of metaseo, no metatags are present. So they get inserted by metaseo.

If it's included, I get tags for DCTERMS.title, date, DCTERMS.date, robots, canonical and some open graph ones.

Overwriting robots is neither possible via setMetaTag nor setCustomMetaTag. Outputting one with key "test" has no effect, and setting openGraph ones is also showing no effect. SetPageTitle does work if the page title cache is disabld via plugin.metaseo.pageTitle.caching = 0

Stepping through the request with debugger I noticed that my extension code is called after the metaseo stuff. I'm trying to use the connector in an extbase plugin controller action should that work? If not, is there a way to rewrite metatags and stuff from controller actions?

**Comment by thomaszbz** [comment]
Metaseo tends to be called multiple times, via hooks.

Metaseo also offers multiple hooks itself. Maybe you can use them to mitigate your race condition.

**Comment by thomaszbz** [comment]
Could you please post a snippet of example code and at which place in your extension you are using it?

**Comment by MK-42** [comment]
Sorry for being so sparse on information and code, I used a touch device for those entries. Let's see what I can provide:

I have a page that contains a plugin of my extension. I want to set metatags and pagetitle depending on stuff in the Controller/Action for that plugin.

```
class DummyController {
    /**
     *
     * @var \Metaseo\Metaseo\Connector
     * @inject
     */
    protected $metaseoConnector = NULL;

    protected function setPageTitle($pageTitle) {
        $this->metaseoConnector->setPageTitle($pageTitle);
        $this->metaseoConnector->setOpenGraphTag("title", $pageTitle);
        $this->metaseoConnector->setMetaTag("robots", "noindex,noarchive,nofollow");
        $this->metaseoConnector->setMetaTag("test", "noindex,noarchive,nofollow");
        $this->metaseoConnector->setCustomMetaTag("robots", "noindex,noarchive,nofollow");
    }

    public function listAction(){
        $this->setPageTitle("ListAction");
    }
}
```

I disabled the pageTitle caching - that resulted in the correct pageTitles. But the og: tags and robots tag is still unchanged (the og:title show the original page title). The new 'test' metatag is also no inserted. As the documentation is really sparse, I don't know if I am using it as intended...

> Does your extension use a static template?

Yes it does. But I couldn't find an order that would help here.

**Comment by thomaszbz** [comment]
@MK-42 I'm not using the connector myself, but what users report back: The connector should work in principle.

@topfender (via #347) Could you please provide some example code to answer this question/share your experience with the connector?

Here's a piece of code @arnekolja posted a while ago on slack:

```
class MyController extends MyBaseController {
    public function showAction($myObj)
    {
        if (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('metaseo')) {
            $connector = $this->objectManager->get('Metaseo\\Metaseo\\Connector');
            $connector->setPageTitle("TEST");
        }
    }
}
```
@MK-42 from what I see is your code not much different from this.

**Comment by topfender** [comment]
This works for me in 7.6 with metaseo 2.1.0 (I'm pretty sure it worked in 2.0.4 as well):

```
public function showAction($myObj) {
    if(\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('metaseo')) {
        $connector = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('Metaseo\\Metaseo\\Connector');
        $title = $this->settings['titleprefix'] . $myObj->getTitle();
        $connector->setPageTitle($title);
        $connector->setMetaTag('title', $title);
        $connector->setOpenGraphTag('title',$title);
        $connector->setMetaTag('keywords', $myObj->getMetakeywords());
        $connector->setMetaTag('description', $myObj->getMetadescription());
    }
}
```

I hope this helps.  You could try to load the connector class via GeneralUtility instead.
I guess everything else is the same.

**Comment by thomaszbz** [comment]
@topfender Thanks for reporting back. Could you recheck if the setMetaTag() function really works as expected (meaning, it really affects output)? That's what @MK-42 reported was not working. It's just that @MK-42 's code should also work in principle.

@topfender Do you have the pagetitle caching enabled or disabled (that's one of MetaSEO's constants which should be used for debugging only)?

@MK-42 One of your question should be answered now: Using a controller to invoke the connector should work. I also think this is a timing issue/race condition. What happens if you don't inject the connector but create it via `objectManager` or TYPO3's `GeneralUtility`, as shown above?

In respect to timing, there is to know that we refactored loading MetaSEO's entry points by a lot in 3.0.0 (for 8 LTS) via #423. That was pure refactoring to get TYPO3 silent in respect to its deprecation log, not with the intention to fix bugs. Most of it could be backported to 7.6 and even 6.2, but isn't. So that's untouched in 2.0.4/2.1.0 releases which is for 6.2 and 7.6. That said, should the 6.2.30 instance of @MK-42 behave like the 7.6 instance of @topfender . To my knowledge, there's ~zero regression potential in 2.0.4/2.1.0 releases in respect to the connector. I had rather expected 3.0.0 (8LTS) to break the connector somewhere, but not 2.1.0 (6.2/7LTS).

@MK-42 There's two new issues now for documentation and tests. This issue is for the potential bug you had. It's still not reproduced. Please report back what your outcome was.

**Comment by topfender** [comment]
setPageTitle, setMetaTag() and setOpenGraphTag() work as expected. I have some default values for them and they get replaced with content from my extension. If the keywords field is empty, the default keywords are used.

I found something while looking through my old code. I added the show action to non cacheable action, because I remember having some issues with wrong content. The connector calls are placed in a difference 'metaAction', which is a cached action. I am not quite sure, why I had to do this. Maybe it didn't work while the action isn't cached.

The project is a few months back, I'm not quite sure why I did things this way. Do you guys need a url to the projectpage to see it in action?

**Comment by thomaszbz** [comment]
Thanks. I think that answers the original question of @MK-42 . Having the action cacheable makes sense because MetaSEO heavily relies on TYPO3's caching framework.

So the problem @MK-42 was faced with presumably was:
- Call Metaseo in cached mode from uncacheable action did not work
- Call Metaseo in uncached mode (Title tag for debug purposes) from uncacheable action worked for the title at least. That explains why for some tags it worked and for some wasn't.

Right would have been to have a cacheable action instead. @MK-42 Can you give that a try?

Seems as if the connector must be called from a cacheable action.

**Comment by thomaszbz** [comment]
@topfender Could you please post such a working example with your cacheable action? I'd like to add this to MetaSEO's documentation via #494.

**Comment by topfender** [comment]
Should I add the snippets here or in #494 ?

**Comment by thomaszbz** [comment]
@topfender I'd go for both ;-) Thanks!

**Comment by topfender** [comment]
How to user metaseo connector class to override page title and meta tags:
Use connector class in a cacheable action:
I would advice to create an extra action, so the plugin can be used in different cases. (e.g. form with extension data over get request).

ext_localconf.php
```
if (!defined('TYPO3_MODE')) {
	die('Access denied.');
}

\TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
	'VENDOR.' . $_EXTKEY,
	'PLUGIN',
	array(
		'MyController' => 'list, show, meta',

	),
	// non-cacheable actions
	array(
		'MyController' => 'show',
	)
);
```

Classes/Controller/MyController.php
```
    /**
     * meta action
     *
     * @param \VENDOR\MyExt\Domain\Model\MyObj $myObj
     * @ignorevalidation $myObj
     * @return void
     */
    public function metaAction(\VENDOR\MyExt\Domain\Model\MyObj $myObj = null) {
        if($myObj) {
            if(\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('metaseo')) {
                $title = trim($this->settings['title']['prefix']." ".$myObj->getTitle()." ".$this->settings['title']['suffix']);
                $connector = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('Metaseo\\Metaseo\\Connector');
                $connector->setPageTitle($title);
                $connector->setMetaTag('title', $title);
                $connector->setOpenGraphTag('title',$title);
                if(trim($myObj->getMetakeywords()) != '') {
                    $connector->setMetaTag('keywords', $myObj->getMetakeywords());
                }
                if(trim($myObj->getMetadescription()) != '') {
                    $connector->setMetaTag('description', $myObj->getMetadescription());
                }
            }
        }
    }
```

The prefix and suffix settings could be set via flexform or typoscript constants if needed.

@thomaszbz please check and correct my spelling and grammar before you add this to the documentation :)

**Comment by thomaszbz** [comment]
@MK-42 Hope that answers it thanks to @topfender .

**Comment by MK-42** [comment]
Sorry for coming back that late on this topic, I hadn't had time to look into this. Thanks for your feedback, I will try implementing the cached metaAction and see if that changes the situation.

**Comment by pipaltree** [comment]
Thanks @topfender for making it clear to use the connector within a cacheable action.
My question regarding your example with the metaAction is: How does this metaAction get called when the showAction is called within this plugin?

**Comment by topfender** [comment]
You could add a second plugin in your backend or add it via TypoScript lib.meta e.g. and with fluid <f:cObject typoscriptObjectPath="lib.meta" /> to your template
